# Generated by Django 5.1.6 on 2025-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('twitter', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('read_minute', models.CharField(max_length=25)),
            ],
        ),
    ]
