# Generated by Django 5.1.6 on 2025-02-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='read_minute',
        ),
    ]
