# Generated by Django 5.1.6 on 2025-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=202)),
                ('image', models.ImageField(upload_to='clients/')),
                ('full_name', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.CharField(max_length=202)),
                ('vision', models.CharField(max_length=202)),
                ('value', models.CharField(max_length=202)),
                ('video', models.FileField(upload_to='team_videos/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
